### ISSUE TITLE
Finalizer is not thread safe and may end up breaking some modules

### ISSUE THREAD

**Issue by 3v1n0** [msteinert/pam#14]
I was trying to an extra test to go-pam, to test the finalizer:

https://github.com/3v1n0/go-pam/commit/693b913

But as you can see from the message, it may not behave as expected.

In fact I feel that calling data finalizers on modules side from a
groutine as SetFinalizer does could create troubles as you can see in
logs from: https://github.com/msteinert/pam/actions/runs/6355635285

PAM per se is thread safe but modules may not and this could be problematic since it's implicitly happening in a goroutine.

So, we decided with @msteinert to just drop this and make usage of `End()` to be explicit.

**Comment by msteinert** [comment]
Now that I think more on this, I wonder if the problem you originally described is really solved. If the goroutine that calls `pam.Start` suspends before `Transaction.End` is called it's possible (even likely) that it may be scheduled on a different OS thread when it continues. It looks like [runtime.LockOSThread][] might help, but I don't think it can be used from within this library. The caller would need to arrrange to lock/unlock the thread at the start/end of the PAM transaction. What do you think?

[runtime.LockOSThread]: https://pkg.go.dev/runtime#LockOSThread

**Comment by 3v1n0** [comment]
I think it has, at least in all the tests I've been doing.

Before we could both end up returning an invalid state or being finalized in a thread different than the calling one.

Indeed things may not go as expected depending how the library is used, but at least we never saw again the crashes at finalization time.
