### ISSUE TITLE
Q: is it possible to use this library in a way

### ISSUE THREAD

**Issue by Idriel** [msteinert/pam#25]
Hi (totally GOLang novice),

is it possible to use this library in a way where I am doing only custom checks to provide passwordless sudo. 
Example: checking few pam.Env variables like SSH_AUTH_USER_0 and few other parameters/checks (not all related to PAM variables). 

if you can give me a little push in right direction what functions to call and how to read PAM Variables and based on then do pam.success or pam.failure:)

It's enough example if pam.env("SSH_AUTH_USER_0") == "pubkey" return pam.success

**Comment by msteinert** [comment]
I think [GetEnv][] and/or [GetEnvList][] are the functions you are looking for?

[GetEnv]: https://pkg.go.dev/github.com/msteinert/pam/v2#Transaction.GetEnv
[GetEnvList]: https://pkg.go.dev/github.com/msteinert/pam/v2#Transaction.GetEnvList
